CREATE VIEW pw.[DatiConsumi]
as
SELECT
	CAST(REPLACE([Canale],'0','') AS [varchar](5)) as [Canale],
	CAST(REPLACE([Cod Agenzia],'0','') AS [varchar](5)) as [CodAgenzia],
	CAST(REPLACE([Cluster Agenzia],'0','') AS [varchar](5)) as [ClusterAgenzia],
	CAST([Cod contratto] AS [varchar](10)) as [CodContratto],
	CAST(REPLACE([Categoria cespite],'0','') AS [varchar](5)) as [CategoriaCespite],
	CAST(REPLACE([Cespite],'0','') AS [varchar](5)) as [Cespite],
	CAST(REPLACE([Tipologia Utenza],'0','') AS [varchar](5)) as [TipologiaUtenza],
	CAST([Data trasf. in entr.] AS [date]) as [DataTrasf.entr.],
	CAST([Data trasf. in usc. (new)] AS [date]) as [DataTrasf.usc.],
	CAST(REPLACE([Motivo blocco calc.],'0','') AS [varchar](5)) as [MotivoBloccoCalc.],
	CAST(REPLACE([Età Anagrafica],'0','') AS [varchar](5)) as [Anagrafica],
	CAST(REPLACE([Settore merceologico],'0','') AS [varchar](5)) as [SettoreMerceologico],
	CAST(REPLACE([Listino Proposto],'0','') AS [varchar](5)) as [ListinoProposto],
	CAST(REPLACE([Soc. Vend. Prec.],'0','') AS [varchar](5)) as [Soc.Vend.Prec.],
	CAST(REPLACE([Cluster Soc Vend],'0','') AS [varchar](5)) as [ClusterSocVend],
	CAST(REPLACE([Località],'0','') AS [varchar](10)) as [Localita],
	CAST(REPLACE([Ind.: Cod.ISTAT Com.],'0','') AS [varchar](10)) as [Cod.ISTAT] ,
	CAST(REPLACE([Provincia],'0','') AS [varchar](10)) as [Provincia] ,
	CAST(REPLACE([Regione Italiana],'0','') AS [varchar](10)) as [RegioneItaliana] ,
	CAST(REPLACE([zona],'0','') AS [varchar](10)) as  [Zona],
	CAST(REPLACE([Modalità di pagamento],'0','') AS [varchar](5)) as [ModoPagamento],
	CAST([Permanenza (mesi)] AS float ) as [Permanenza],
	CAST([Consumo medio annuo] AS float) as [ConsumoMedio_annuo],
	CAST([Consumo totale] AS float ) as [ConsumoTotale],
	CAST([Margine fisso QF annua] AS float ) as [MargineFissoQF_annuo],
	CAST([Margine fisso totale] AS float) as [MargineFissoTotale],
	CAST([Margine variabile QV] AS float ) as [MargineVariabileQV],
	CAST([Margine variabile QV annuo] AS float ) as [MargineVariabileQV_annuo],
	CAST([Margine variabile totale] AS float) as [MargineVariabileTotale],
	CAST([Margine totale] AS float ) as [MargineTotale],
	CAST([Provvigioni (€/swin)] AS float ) as [Provvigioni],
	CAST([Acquisizione] AS float ) as [Acquisizione],
	CAST([Costo annuo Post-vendita e Customer care] AS float ) as [CostoAnnuo_Post-vendita_Customer-care],
	CAST([Reddito totale] AS float) as [Reddito totale],
	CAST(ISNULL([Mese 1] ,0.00)AS float  ) as Mese01,
	CAST(ISNULL([Mese 2] ,0.00)AS float  ) as Mese02,
	CAST(ISNULL([Mese 3] ,0.00) AS float ) as Mese03,
	CAST(ISNULL([Mese 4] ,0.00) AS float ) as Mese04,
	CAST(ISNULL([Mese 5] ,0.00) AS float ) as Mese05,
	CAST(ISNULL([Mese 6] ,0.00) AS float ) as Mese06,
	CAST(ISNULL([Mese 7] ,0.00) AS float ) as Mese07,
	CAST(ISNULL([Mese 8] ,0.00) AS float ) as Mese08,
	CAST(ISNULL([Mese 9] ,0.00) AS float ) as Mese09,
	CAST(ISNULL([Mese 10],0.00) AS float ) as Mese10,
	CAST(ISNULL([Mese 11],0.00) AS float ) as Mese11,
	CAST(ISNULL([Mese 12],0.00) AS float ) as Mese12,
	CAST(ISNULL([Mese 13],0.00) AS float ) as Mese13,
	CAST(ISNULL([Mese 14],0.00) AS float ) as Mese14,
	CAST(ISNULL([Mese 15],0.00) AS float ) as Mese15,
	CAST(ISNULL([Mese 16],0.00) AS float ) as Mese16,
	CAST(ISNULL([Mese 17],0.00) AS float ) as Mese17,
	CAST(ISNULL([Mese 18],0.00) AS float ) as Mese18,
	CAST(ISNULL([Mese 19],0.00) AS float ) as Mese19,
	CAST(ISNULL([Mese 20],0.00) AS float ) as Mese20,
	CAST(ISNULL([Mese 21],0.00) AS float ) as Mese21,
	CAST(ISNULL([Mese 22],0.00) AS float ) as Mese22,
	CAST(ISNULL([Mese 23],0.00) AS float ) as Mese23,
	CAST(ISNULL([Mese 24],0.00) AS float ) as Mese24,
	CAST(ISNULL([Mese 25],0.00) AS float ) as Mese25,
	CAST(ISNULL([Mese 26],0.00) AS float ) as Mese26,
	CAST(ISNULL([Mese 27],0.00) AS float ) as Mese27,
	CAST(ISNULL([Mese 28],0.00) AS float ) as Mese28,
	CAST(ISNULL([Mese 29],0.00) AS float ) as Mese29,
	CAST(ISNULL([Mese 30],0.00) AS float ) as Mese30,
	CAST(ISNULL([Mese 31],0.00) AS float ) as Mese31,
	CAST(ISNULL([Mese 32],0.00) AS float ) as Mese32,
	CAST(ISNULL([Mese 33],0.00) AS float ) as Mese33,
	CAST(ISNULL([Mese 34],0.00) AS float ) as Mese34,
	CAST(ISNULL([Mese 35],0.00) AS float ) as Mese35,
	CAST(ISNULL([Mese 36],0.00) AS float ) as Mese36,
	CAST(ISNULL([Mese 37],0.00) AS float ) as Mese37,
	CAST(ISNULL([Mese 38],0.00) AS float ) as Mese38,
	CAST(ISNULL([Mese 39],0.00) AS float ) as Mese39,
	CAST(ISNULL([Mese 40],0.00) AS float ) as Mese40,
	CAST(ISNULL([Mese 41],0.00) AS float ) as Mese41,
	CAST(ISNULL([Mese 42],0.00) AS float ) as Mese42,
	CAST(ISNULL([Mese 43],0.00) AS float ) as Mese43,
	CAST(ISNULL([Mese 44],0.00) AS float ) as Mese44,
	CAST(ISNULL([Mese 45],0.00) AS float ) as Mese45,
	CAST(ISNULL([Mese 46],0.00) AS float ) as Mese46,
	CAST(ISNULL([Mese 47],0.00) AS float ) as Mese47,
	CAST(ISNULL([Mese 48],0.00) AS float ) as Mese48,
	CAST(ISNULL([Mese 49],0.00) AS float ) as Mese49,
	CAST(ISNULL([Mese 50],0.00) AS float ) as Mese50,
	CAST(ISNULL([Mese 51],0.00) AS float ) as Mese51,
	CAST(ISNULL([Mese 52],0.00) AS float ) as Mese52,
	CAST(ISNULL([Mese 53],0.00) AS float ) as Mese53,
	CAST(ISNULL([Mese 54],0.00) AS float ) as Mese54,
	CAST(ISNULL([Mese 55],0.00) AS float ) as Mese55,
	CAST(ISNULL([Mese 56],0.00) AS float ) as Mese56,
	CAST(ISNULL([Mese 57],0.00) AS float ) as Mese57,
	CAST(ISNULL([Mese 58],0.00) AS float ) as Mese58,
	CAST(ISNULL([Mese 59],0.00) AS float ) as Mese59,
	CAST(ISNULL([Mese 60],0.00) AS float ) as Mese60,
	CAST([Mesi BEP] AS [tinyint]) as MesiBEP,
	CAST([Mesi attivi] AS [tinyint]) as MesiAttivi,
	CAST([Reddito complessivo 5 anni] AS float) as UltimoReddito,
	CASE
	WHEN [BEP] like '%02' THEN 1
	ELSE 0
	END AS BEP
FROM [lab10].[DatiConsumi]
	
	;
	GO


CREATE VIEW pw.DatiConsumi_view
as
SELECT
	CAST(REPLACE([Canale],'0','') AS [varchar](5)) as [Canale],
	CAST(REPLACE([Cod Agenzia],'0','') AS [varchar](5)) as [CodAgenzia],
	CAST(REPLACE([Cluster Agenzia],'0','') AS [varchar](5)) as [ClusterAgenzia],
	CAST([Cod contratto] AS [varchar](10)) as [CodContratto],
	CAST(REPLACE([Categoria cespite],'0','') AS [varchar](5)) as [CategoriaCespite],
	CAST(REPLACE([Cespite],'0','') AS [varchar](5)) as [Cespite],
	CAST(REPLACE([Tipologia Utenza],'0','') AS [varchar](5)) as [TipologiaUtenza],
	CAST([Data trasf. in entr.] AS [date]) as [DataTrasf.entr.],
	CAST([Data trasf. in usc. (new)] AS [date]) as [DataTrasf.usc.],
	CAST(REPLACE([Motivo blocco calc.],'0','') AS [varchar](5)) as [MotivoBloccoCalc.],
	CAST(REPLACE([Età Anagrafica],'0','') AS [varchar](5)) as [Anagrafica],
	CAST(REPLACE([Settore merceologico],'0','') AS [varchar](5)) as [SettoreMerceologico],
	CAST(REPLACE([Listino Proposto],'0','') AS [varchar](5)) as [ListinoProposto],
	CAST(REPLACE([Soc. Vend. Prec.],'0','') AS [varchar](5)) as [Soc.Vend.Prec.],
	CAST(REPLACE([Cluster Soc Vend],'0','') AS [varchar](5)) as [ClusterSocVend],
	CAST(REPLACE([Località],'0','') AS [varchar](10)) as [Localita],
	CAST(REPLACE([Ind.: Cod.ISTAT Com.],'0','') AS [varchar](10)) as [Cod.ISTAT] ,
	CAST(REPLACE([Provincia],'0','') AS [varchar](10)) as [Provincia] ,
	CAST(REPLACE([Regione Italiana],'0','') AS [varchar](10)) as [RegioneItaliana] ,
	CAST(REPLACE([zona],'0','') AS [varchar](10)) as  [Zona],
	CAST(REPLACE([Modalità di pagamento],'0','') AS [varchar](5)) as [ModoPagamento],
	CAST([Permanenza (mesi)] AS float ) as [Permanenza],
	CAST([Consumo medio annuo] AS float) as [ConsumoMedio_annuo],
	CAST([Consumo totale] AS float ) as [ConsumoTotale],
	CAST([Margine fisso QF annua] AS float ) as [MargineFissoQF_annuo],
	CAST([Margine fisso totale] AS float) as [MargineFissoTotale],
	CAST([Margine variabile QV] AS float ) as [MargineVariabileQV],
	CAST([Margine variabile QV annuo] AS float ) as [MargineVariabileQV_annuo],
	CAST([Margine variabile totale] AS float) as [MargineVariabileTotale],
	CAST([Margine totale] AS float ) as [MargineTotale],
	CAST([Provvigioni (€/swin)] AS float ) as [Provvigioni],
	CAST([Acquisizione] AS float ) as [Acquisizione],
	CAST([Costo annuo Post-vendita e Customer care] AS float ) as [CostoAnnuo_Post-vendita_Customer-care],
	CAST([Reddito totale] AS float) as [Reddito totale],
	CAST([Mese 1] AS float  ) as Mese01,
	CAST([Mese 2] AS float  ) as Mese02,
	CAST([Mese 3]  AS float ) as Mese03,
	CAST([Mese 4]  AS float ) as Mese04,
	CAST([Mese 5]  AS float ) as Mese05,
	CAST([Mese 6]  AS float ) as Mese06,
	CAST([Mese 7]  AS float ) as Mese07,
	CAST([Mese 8]  AS float ) as Mese08,
	CAST([Mese 9]  AS float ) as Mese09,
	CAST([Mese 10] AS float ) as Mese10,
	CAST([Mese 11] AS float ) as Mese11,
	CAST([Mese 12] AS float ) as Mese12,
	CAST([Mese 13] AS float ) as Mese13,
	CAST([Mese 14] AS float ) as Mese14,
	CAST([Mese 15] AS float ) as Mese15,
	CAST([Mese 16] AS float ) as Mese16,
	CAST([Mese 17] AS float ) as Mese17,
	CAST([Mese 18] AS float ) as Mese18,
	CAST([Mese 19] AS float ) as Mese19,
	CAST([Mese 20] AS float ) as Mese20,
	CAST([Mese 21] AS float ) as Mese21,
	CAST([Mese 22] AS float ) as Mese22,
	CAST([Mese 23] AS float ) as Mese23,
	CAST([Mese 24] AS float ) as Mese24,
	CAST([Mese 25] AS float ) as Mese25,
	CAST([Mese 26] AS float ) as Mese26,
	CAST([Mese 27] AS float ) as Mese27,
	CAST([Mese 28] AS float ) as Mese28,
	CAST([Mese 29] AS float ) as Mese29,
	CAST([Mese 30] AS float ) as Mese30,
	CAST([Mese 31] AS float ) as Mese31,
	CAST([Mese 32] AS float ) as Mese32,
	CAST([Mese 33] AS float ) as Mese33,
	CAST([Mese 34] AS float ) as Mese34,
	CAST([Mese 35] AS float ) as Mese35,
	CAST([Mese 36] AS float ) as Mese36,
	CAST([Mese 37] AS float ) as Mese37,
	CAST([Mese 38] AS float ) as Mese38,
	CAST([Mese 39] AS float ) as Mese39,
	CAST([Mese 40] AS float ) as Mese40,
	CAST([Mese 41] AS float ) as Mese41,
	CAST([Mese 42] AS float ) as Mese42,
	CAST([Mese 43] AS float ) as Mese43,
	CAST([Mese 44] AS float ) as Mese44,
	CAST([Mese 45] AS float ) as Mese45,
	CAST([Mese 46] AS float ) as Mese46,
	CAST([Mese 47] AS float ) as Mese47,
	CAST([Mese 48] AS float ) as Mese48,
	CAST([Mese 49] AS float ) as Mese49,
	CAST([Mese 50] AS float ) as Mese50,
	CAST([Mese 51] AS float ) as Mese51,
	CAST([Mese 52] AS float ) as Mese52,
	CAST([Mese 53] AS float ) as Mese53,
	CAST([Mese 54] AS float ) as Mese54,
	CAST([Mese 55] AS float ) as Mese55,
	CAST([Mese 56] AS float ) as Mese56,
	CAST([Mese 57] AS float ) as Mese57,
	CAST([Mese 58] AS float ) as Mese58,
	CAST([Mese 59] AS float ) as Mese59,
	CAST([Mese 60] AS float ) as Mese60,
	CAST([Mesi BEP] AS [tinyint]) as MesiBEP,
	CAST([Mesi attivi] AS [tinyint]) as MesiAttivi,
	CAST([Reddito complessivo 5 anni] AS float) as UltimoReddito,
	CASE
	WHEN [BEP] like '%02' THEN 1
	ELSE 0
	END AS BEP
FROM [lab10].[DatiConsumi]

select TOP 100 * from pw.DatiConsumi_view


/*
CREATE VIEW pw.FactConsumi

CREATE VIEW pw.Dim
*/