CREATE VIEW pw.[DatiConsumi]
as
SELECT
	CAST([Canale] AS [varchar](10)) as [Canale],
	CAST([Cod Agenzia] AS [varchar](10)) as [CodAgenzia],
	CAST([Cluster Agenzia] AS [varchar](10)) as [ClusterAgenzia],
	CAST([Cod contratto] AS [varchar](10)) as [CodContratto],
	CAST([Categoria cespite] AS [varchar](10)) as [CategoriaCespite],
	CAST([Cespite] AS [varchar](10)) as [Cespite],
	CAST([Tipologia Utenza] AS [varchar](10)) as [TipologiaUtenza],
	CAST([Data trasf. in entr.] AS [date]) as [DataTrasf.entr.],
	CAST([Data trasf. in usc. (new)] AS [date]) as [DataTrasf.usc.],
	CAST([Motivo blocco calc.] AS [varchar](10)) as [MotivoBloccoCalc.],
	CAST([Età Anagrafica] AS [varchar](10)) as [Anagrafica],
	CAST([Settore merceologico] AS [varchar](10)) as [SettoreMerceologico],
	CAST([Listino Proposto] AS [varchar](10)) as [ListinoProposto],
	CAST([Soc. Vend. Prec.] AS [varchar](10)) as [Soc.Vend.Prec.],
	CAST([Cluster Soc Vend] AS [varchar](10)) as [ClusterSocVend],
	CAST([Modalità di pagamento] AS [varchar](10)) as [ModoPagamento],
	CAST([Permanenza (mesi)] AS float ) as [Permanenza],
	CAST([Consumo medio annuo] AS float) as [ConsumoMedio_annuo],
	CAST([Consumo totale] AS float ) as [ConsumoTotale],
	CAST([Margine fisso QF annua] AS float ) as [MargineFissoQF_annuo],
	CAST([Margine fisso totale] AS float) as [MargineFissoTotale],
	CAST([Margine variabile QV] AS float ) as [MargineVariabileQV],
	CAST([Margine variabile QV annuo] AS float ) as [MargineVariabileQV_annuo],
	CAST([Margine variabile totale] AS float) as [MargineVariabileTotale],
	CAST([Margine totale] AS float ) as [MargineTotale],
	CAST([Provvigioni (€/swin)] AS float ) as [Provvigioni],
	CAST([Acquisizione] AS float ) as [Acquisizione],
	CAST([Costo annuo Post-vendita e Customer care] AS float ) as [CostoAnnuo_Post-vendita_Customer-care],
	CAST([Reddito totale] AS float) as [Reddito totale],
	CAST(ISNULL([Mese 1] ,0.00)AS float  ) as Mese01,
	CAST(ISNULL([Mese 2] ,0.00)AS float  ) as Mese02,
	CAST(ISNULL([Mese 3] ,0.00) AS float ) as Mese03,
	CAST(ISNULL([Mese 4] ,0.00) AS float ) as Mese04,
	CAST(ISNULL([Mese 5] ,0.00) AS float ) as Mese05,
	CAST(ISNULL([Mese 6] ,0.00) AS float ) as Mese06,
	CAST(ISNULL([Mese 7] ,0.00) AS float ) as Mese07,
	CAST(ISNULL([Mese 8] ,0.00) AS float ) as Mese08,
	CAST(ISNULL([Mese 9] ,0.00) AS float ) as Mese09,
	CAST(ISNULL([Mese 10],0.00) AS float ) as Mese10,
	CAST(ISNULL([Mese 11],0.00) AS float ) as Mese11,
	CAST(ISNULL([Mese 12],0.00) AS float ) as Mese12,
	CAST(ISNULL([Mese 13],0.00) AS float ) as Mese13,
	CAST(ISNULL([Mese 14],0.00) AS float ) as Mese14,
	CAST(ISNULL([Mese 15],0.00) AS float ) as Mese15,
	CAST(ISNULL([Mese 16],0.00) AS float ) as Mese16,
	CAST(ISNULL([Mese 17],0.00) AS float ) as Mese17,
	CAST(ISNULL([Mese 18],0.00) AS float ) as Mese18,
	CAST(ISNULL([Mese 19],0.00) AS float ) as Mese19,
	CAST(ISNULL([Mese 20],0.00) AS float ) as Mese20,
	CAST(ISNULL([Mese 21],0.00) AS float ) as Mese21,
	CAST(ISNULL([Mese 22],0.00) AS float ) as Mese22,
	CAST(ISNULL([Mese 23],0.00) AS float ) as Mese23,
	CAST(ISNULL([Mese 24],0.00) AS float ) as Mese24,
	CAST(ISNULL([Mese 25],0.00) AS float ) as Mese25,
	CAST(ISNULL([Mese 26],0.00) AS float ) as Mese26,
	CAST(ISNULL([Mese 27],0.00) AS float ) as Mese27,
	CAST(ISNULL([Mese 28],0.00) AS float ) as Mese28,
	CAST(ISNULL([Mese 29],0.00) AS float ) as Mese29,
	CAST(ISNULL([Mese 30],0.00) AS float ) as Mese30,
	CAST(ISNULL([Mese 31],0.00) AS float ) as Mese31,
	CAST(ISNULL([Mese 32],0.00) AS float ) as Mese32,
	CAST(ISNULL([Mese 33],0.00) AS float ) as Mese33,
	CAST(ISNULL([Mese 34],0.00) AS float ) as Mese34,
	CAST(ISNULL([Mese 35],0.00) AS float ) as Mese35,
	CAST(ISNULL([Mese 36],0.00) AS float ) as Mese36,
	CAST(ISNULL([Mese 37],0.00) AS float ) as Mese37,
	CAST(ISNULL([Mese 38],0.00) AS float ) as Mese38,
	CAST(ISNULL([Mese 39],0.00) AS float ) as Mese39,
	CAST(ISNULL([Mese 40],0.00) AS float ) as Mese40,
	CAST(ISNULL([Mese 41],0.00) AS float ) as Mese41,
	CAST(ISNULL([Mese 42],0.00) AS float ) as Mese42,
	CAST(ISNULL([Mese 43],0.00) AS float ) as Mese43,
	CAST(ISNULL([Mese 44],0.00) AS float ) as Mese44,
	CAST(ISNULL([Mese 45],0.00) AS float ) as Mese45,
	CAST(ISNULL([Mese 46],0.00) AS float ) as Mese46,
	CAST(ISNULL([Mese 47],0.00) AS float ) as Mese47,
	CAST(ISNULL([Mese 48],0.00) AS float ) as Mese48,
	CAST(ISNULL([Mese 49],0.00) AS float ) as Mese49,
	CAST(ISNULL([Mese 50],0.00) AS float ) as Mese50,
	CAST(ISNULL([Mese 51],0.00) AS float ) as Mese51,
	CAST(ISNULL([Mese 52],0.00) AS float ) as Mese52,
	CAST(ISNULL([Mese 53],0.00) AS float ) as Mese53,
	CAST(ISNULL([Mese 54],0.00) AS float ) as Mese54,
	CAST(ISNULL([Mese 55],0.00) AS float ) as Mese55,
	CAST(ISNULL([Mese 56],0.00) AS float ) as Mese56,
	CAST(ISNULL([Mese 57],0.00) AS float ) as Mese57,
	CAST(ISNULL([Mese 58],0.00) AS float ) as Mese58,
	CAST(ISNULL([Mese 59],0.00) AS float ) as Mese59,
	CAST(ISNULL([Mese 60],0.00) AS float ) as Mese60,
	CAST([Mesi BEP] AS [tinyint]) as MesiBEP,
	CAST([Mesi attivi] AS [tinyint]) as MesiAttivi,
	CAST([Reddito complessivo 5 anni] AS float) as UltimoReddito,
	CASE
	WHEN [BEP] like '%02' THEN 1
	ELSE 0
	END AS BEP
FROM [lab10].[DatiConsumi]
	
	;
	GO

CREATE VIEW pw.FactConsumi

CREATE VIEW pw.Dim